[project]
name = "polymer-md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Reina234", email = "zhengreina@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "acpype>=2023.10.27",
    "matplotlib>=3.10.8",
    "openbabel-wheel>=3.1.1.23",
    "parmed>=4.3.1",
    "pydantic>=2.12.5",
    "pylint-pydantic>=0.4.1",
    "pytest>=9.0.3",
    "rdkit>=2024.3.1,<=2025.9.3",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
]


[project.scripts]
polymer-md = "polymer_md:main"

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"
